name: docker push
on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

permissions:
  contents: read # for checkout

jobs:
  docker:
    name: Push to docker hub
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Tags
        id: tags
        run: |
          git fetch --tags
          echo "Tags fetched"

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "Tag name from TAG NAME: $(git describe --tags `git rev-list --tags --max-count=1`)"

